on: push
name: CI Build & Test
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          push: false
      - name: Build Kubermatic Addon Image
        uses: docker/build-push-action@v2
        with:
          context: ./kubermatic-addon
          push: false
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - run: go test ./...
        name: Run Tests
